apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blog
  name: blog
  namespace: default
spec:
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      volumes:
      - name: le-certs
        secret:
          secretName: le-certs
      - name: nginx-cm
        configMap:
          name: nginx-conf
      - name: tmp
        emptyDir: {}
      - name: run
        emptyDir: {}
      containers:
      - image: ghcr.io/reberp/personal-blog
      #- image: ghcr.io/reberp/test
        imagePullPolicy: Always
        name: blog
        volumeMounts:
        - mountPath: /etc/nginx/ssl/
          name: le-certs
        - mountPath: /etc/nginx/conf.d
          name: nginx-cm
        - name: run
          mountPath: /var/run
        - name: tmp
          mountPath: /var/lib/nginx/tmp/
        securityContext:
          readOnlyRootFilesystem: true
  replicas: 1
