apiVersion: v1
data:
  default.conf: |-
      server {
          listen 8443 ssl;
          server_name patrickreber.com;

          #ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
          #ssl_certificate /etc/nginx/ssl/fullchain.pem;
          #ssl_certificate_key /etc/nginx/ssl/privkey.key;
          ssl_certificate /etc/nginx/ssl/tls.crt;
          ssl_certificate_key /etc/nginx/ssl/tls.key;
  
          location / {
              root /usr/share/nginx/html;
              index index.html;
          }
      }
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: blog
