apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blog
  namespace: blog
spec:
  prune: true
  interval: 1m
  sourceRef:
    kind: OCIRepository
    name: blog
    namespace: blog
